Updated files (incl. Error + Admin .html
Aareon/sarp-cad pull request #9
Opened 2018-02-13 15:33 UTC by HarryjosephSARP

2018-02-13 17:03 UTC, HarryjosephSARP commented
Added correct variable syntax

2018-02-13 18:39 UTC, Aareon requested changes
Please correct these so that I can merge.

2018-02-13 18:39 UTC, Aareon commented on static/styles/style.css
> +  src: url("fonts/pricedown.woff") format("woff"), url("../fonts/pricedown.otf") format("opentype"), url("../fonts/pricedown.svg#filename") format("svg");
missing `../` in `url("../fonts/pricedown.woff")

2018-02-13 18:39 UTC, Aareon commented on templates/index.html
>    <!--<img class="image-top" src="image/banner.png" alt=""> -->
Title should be `Computer Aided Dispatch`, not `Computer-aided design`. This goes for all files.

2018-02-13 18:39 UTC, Aareon commented on templates/admin.html
> +            <td>Harry</td>
Please don't hard-code values like these.

2018-02-13 18:39 UTC, Aareon commented on templates/admin.html
> +            <td>Harry (1B-03)</td>
And here

2018-02-13 18:39 UTC, Aareon commented on templates/dispatch.html
> +          Reason: {reason} <br> Location: {location} <br> Details: {details}<br> On-scene Units: {units} <br>
Needs proper Flask syntax. i.e. `{{reason}}`

2018-02-13 18:46 UTC, Aareon approved these changes

2018-02-13 18:50 UTC, Aareon requested changes

2018-02-13 18:50 UTC, Aareon commented on templates/admin.html
> +            <td>{{user} (1B-03)</td>
Think you missed something here. I'll end up generating this table myself, so really just leave one column with the variables and I'll handle the rest.

2018-02-13 20:55 UTC, Aareon requested changes

2018-02-13 20:55 UTC, Aareon commented on templates/admin.html
> +            <td>{{username}} (1B-03)</td>
Left your badge number.

2018-02-14 02:45 UTC, Aareon commented
Please alter this PR to fit the latest commits.

2018-02-15 22:55 UTC, Aareon approved these changes

2018-02-15 22:55 UTC, merged